"""Add last_active column

Revision ID: 3f3ef9fe2fda
Revises: 
Create Date: 2026-03-04 19:31:13.615132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3ef9fe2fda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # in your migration file
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active')
    # ### end Alembic commands ###
